github actions validate

diff --git a/.github/workflows/Awesome-Game-Analysis.yml b/.github/workflows/Awesome-Game-Analysis.yml
--- a/.github/workflows/Awesome-Game-Analysis.yml
+++ b/.github/workflows/Awesome-Game-Analysis.yml
@@ -1,7 +1,7 @@
 # This workflow will install Python dependencies, run tests and lint with a single version of Python
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
-name: Awesome-Game-Analysis-auto
+name: Awesome-Game-Analysis
 
 on:
   push:
@@ -27,4 +27,19 @@ jobs:
           pip install -r scripts/requirements.txt
 
       - name: Execute Python scripts
-        run: python scripts/toml_markdown.py -i games.toml -t toml --readme > README.md
+        run: python scripts/toml_markdown.py -i games.toml -t toml --readme 
+
+      - name: Commit changes
+        run: |
+          if [ "${{ steps.execute-scripts.outcome }}" == "success" ]; then
+            commit_message="${{ steps.get-commit-message.outputs.commit-message }}"
+            git config --global user.name "K1ngst0m"
+            git config --global user.email "kingstom.chen@gmail.com"
+            git add .
+            git commit -m "$commit_message"
+            git push
+          else
+            echo "Execution failed. Exiting."
+            exit 1
+          fi
+      
